# Generated by Django 4.1.7 on 2023-08-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_demande_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='article',
        ),
    ]
