# Generated by Django 4.1.7 on 2023-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_remove_demande_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='remarque',
            field=models.TextField(null=True),
        ),
    ]
