# Generated by Django 4.1.7 on 2023-08-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_alter_membres_tel'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='article',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='quantite',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.departement'),
        ),
    ]
