# Generated by Django 4.1.7 on 2023-08-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_alter_membres_tel'),
        ('dispatch', '0002_remove_dispatch_article_remove_dispatch_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.membres'),
        ),
    ]
