# Generated by Django 4.1.7 on 2023-07-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='membres',
            name='tel',
            field=models.CharField(default='aucun', max_length=11),
        ),
        migrations.AlterField(
            model_name='membres',
            name='mot_de_passe',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='membres',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.admin'),
        ),
        migrations.AddField(
            model_name='membres',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.departement'),
        ),
        migrations.AddField(
            model_name='membres',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.service'),
        ),
    ]
